### ISSUE TITLE
exception corruption in compiled 'with'

### ISSUE THREAD

**Issue by rubidge** [APrioriInvestments/typed_python#359]
Given
```
        class CM():
            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc_val, exc_tb):
                return True

        def f():
            with CM():
                raise NotImplementedError()
```
this code
```
        def repeat_a():
            for i in range(1000):
                try:
                    f()
                except Exception as e:
                    pass
            return 1/0
```
produces ZeroDivisionError, as expected.

But this code
```
        def repeat_b():
            for i in range(1000):
                try:
                    Compiled(f)()
                except Exception as e:
                    pass
            return 1/0
```
does not produce ZeroDivisionError.  Instead, it produces NotImplementedError x 1000, then 'RecursionError: maximum recursion depth exceeded while calling a Python object',

```
Traceback (most recent call last):
  File "/home/jeff/repos/typed_python/typed_python/compiler/tests/conversion_test.py", line 2444, in f
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeff/repos/typed_python/typed_python/compiler/tests/conversion_test.py", line 2444, in f
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeff/repos/typed_python/typed_python/compiler/tests/conversion_test.py", line 2444, in f
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

... (997 more) ...

Traceback (most recent call last):
  File "/home/jeff/repos/typed_python/.venv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 125, in main
    config=config
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/_pytest/main.py", line 213, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 864, in notify_exception
    funcargs=True, showlocals=getattr(option, "showlocals", False), style=style
  File "/home/jeff/repos/typed_python/.venv/lib/python3.6/site-packages/_pytest/_code/code.py", line 619, in getrepr
    self.type, self.value, self.traceback[0]._rawentry
  File "/usr/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 498, in __init__
    _seen=_seen)
  File "/usr/lib/python3.6/traceback.py", line 498, in __init__
    _seen=_seen)
  File "/usr/lib/python3.6/traceback.py", line 498, in __init__
    _seen=_seen)
  [Previous line repeated 243 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

```
If range(1000) is replaced with range(100), just get ZeroDivisionError.

So this seems to be a corruption problem with handling the exceptions in the compiled code, erroneously chaining exceptions that should be independent.

Going to revert some code and retest this case.

**Comment by rubidge** [comment]
Pretty sure this is my own bug, that wasn't visible before due to an error in my tests.

**Comment by braxtonmckee** [comment]
@rubidge  can you reconfirm this? I found a bug in the interpreter handling of '__exit__' on classes causing memory corruption. maybe that will fix this?

**Comment by rubidge** [comment]
It fixes `test_with_exception` from jeff-with3.  I'll include that test in the next pull request.  Will check that this fixes other tests that I had been avoiding... I'll try to get the multiple context managers in one line working too.

**Comment by braxtonmckee** [comment]
so multiple context managers in one line works now. but if you can just
confirm that none of your old segfaults exist (and add tests) that would be
awesome.

whenever you fix a low-level but like that, hard to know what other bugs
were a consequence

**Comment by rubidge** [comment]
Will add those tests.  Not seeing the exception chaining problem any more.
But I do see a problem with multiple context managers on one line.  Since
they end up using the same variable names for hit_except, etc., they can
interfere with each other.  It's not hard to give them unique names, but
even then a few cases fail (specifically, when the inner CM raises during
__exit__ and the outer CM tries to suppress it).  I'll make a clear test
for those cases.

**Comment by rubidge** [comment]
It was the same problem with 'try'.  After rewriting 'with CM1, CM2:' as 'try: try:' we end up with two 'try' statements on the same line, resulting in colliding variables when compiling the trys.  This can be corrected easily.

**Comment by braxtonmckee** [comment]
Great - thanks for picking up on taht
